config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :visitors
  root to: "visitors#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :visitor, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable,
         :confirmable,
         :trackable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_visitor, only: %i[ show edit update destroy ]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.all
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = current_user.visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = current_user.visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:name, :document, :telefone, :sector, :localuser, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_account_links.html.erb
<% if user_signed_in? %>

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/layouts/_topnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Recepção Vice Governadoria  </a>
 

<ul></ul>

      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button> <ul></ul>
      <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="">
      
    </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atendimento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <main class="container">

  <body>
    <%= yield %>
  </body>
  </main>
</html>

app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :document %>
    <%= form.text_field :document %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :sector %>
    <%= form.text_field :sector %>
  </div>

  <div class="field">
    <%= form.label :localuser %>
    <%= form.text_field :localuser %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visitors/_topnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Recepção Vice Governadoria  </a>
 

<ul></ul>

      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button> <ul></ul>
      <input class="form-control mr-sm-2" type="search" placeholder="" aria-label="">
      
    </form>
</nav>

app/views/visitors/edit.html.erb
<h1>Editing Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Show', @visitor %> |
<%= link_to 'Back', visitors_path %>

app/views/visitors/index.html.erb
<%= render 'topnavbar', visitor: @visitor %>

<p id="notice"><%= notice %></p>

<h1>Visitantes</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Documento</th>
      <th>Telefone</th>
      <th>Setor</th>
      <th>Colaborador ViceGov</th>
      <th>Data de Registro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.name %></td>
        <td><%= visitor.document %></td>
        <td><%= visitor.telefone %></td>
        <td><%= visitor.sector %></td>
        <td><%= visitor.localuser %></td>
        <td><%= visitor.created_at %></td>
        <td><%= link_to 'Show', visitor %></td>
        <td><%= link_to 'Edit', edit_visitor_path(visitor) %></td>
        <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


 <%= link_to 'Nova Visita', new_visitor_path, class: 'btn btn-outline-primary' %>

app/views/visitors/new.html.erb
<h1>New Visitor</h1>

<%= render 'form', visitor: @visitor %>

<%= link_to 'Back', visitors_path %>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @visitor.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @visitor.document %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @visitor.telefone %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @visitor.sector %>
</p>

<p>
  <strong>Localuser:</strong>
  <%= @visitor.localuser %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>